import '@mantine/core/styles.css';
import { Providers } from '@/providers/Providers';
import { ColorSchemeScript } from '@mantine/core';
import './globals.css';

export const metadata = {
  title: 'Next.js + TanStack Router + Mantine',
  description: 'Starter kit generated by Antigravity',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
